# Site settings
title: borigil's blog
email: borigil@adqua.co.kr
baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://borigil.github.io/" # the base hostname & protocol for your site

# Sidebar settings
description: AdQUA front-end developer borigil

# Social icons
facebook: byungkil.park
github: borigil@adqua.co.kr
codepen: borigil

footer: © borigil, AdQUA interactive

# Build settings
markdown: kramdown
